# ServiceAccount and RBAC needed to install Istio (ambient profile). Adjust if your cluster requires stricter policies.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-deployer-sa
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-deployer-clusterrole
rules:
  # core namespace-scoped objects
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - services
      - endpoints
      - configmaps
      - secrets
      - serviceaccounts
    verbs: ["*"]
  # workloads
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["*"]
  # RBAC objects (create ClusterRole/Binding etc.)
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs: ["*"]
  # CRDs
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs: ["*"]
  # Istio/operator CRDs and resources
  - apiGroups: ["install.istio.io", "networking.istio.io", "security.istio.io"]
    resources: ["*"]
    verbs: ["*"]
  # Admission webhooks
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: ["*"]
  # cluster-wide objects often created by istio
  - apiGroups: [""]
    resources:
      - nodes
    verbs: ["get","list","watch"]
  # allow creation/management of cluster-scoped services (e.g. ServiceAccounts in other namespaces)
  - apiGroups: [""]
    resources:
      - persistentvolumeclaims
      - persistentvolumes
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-deployer-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: istio-deployer-sa
    namespace: istio-system
roleRef:
  kind: ClusterRole
  name: istio-deployer-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
# Optional: namespace-scoped Role for istio-system (redundant if ClusterRole used, kept for clusters that require explicit namespace RoleBindings)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-deployer-namespace-role
  namespace: istio-system
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
      - secrets
      - endpoints
      - serviceaccounts
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
    verbs: ["*"]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-deployer-namespace-binding
  namespace: istio-system
subjects:
  - kind: ServiceAccount
    name: istio-deployer-sa
    namespace: istio-system
roleRef:
  kind: Role
  name: istio-deployer-namespace-role
  apiGroup: rbac.authorization.k8s.io